# Generated by Django 5.1.2 on 2024-10-15 04:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Name should start with 'Dr.'", regex='^Dr\\.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('category', models.CharField(choices=[('CARDIOLOGIST', 'cardiologist'), ('cardiologist', 'cardiologist'), ('CARDIOLOGIST', 'CARDIOLOGIST'), ('DERMATOLOGIST', 'dermatologist'), ('dermatologist', 'dermatologist'), ('DERMATOLOGIST', 'DERMATOLOGIST'), ('ENDOCRINOLOGIST', 'endocrinologist'), ('endocrinologist', 'endocrinologist'), ('ENDOCRINOLOGIST', 'ENDOCRINOLOGIST'), ('GASTROENTEROLOGIST', 'gastroenterologist'), ('gastroenterologist', 'gastroenterologist'), ('GASTROENTEROLOGIST', 'GASTROENTEROLOGIST'), ('HEMATOLOGIST', 'hematologist'), ('hematologist', 'hematologist'), ('HEMATOLOGIST', 'HEMATOLOGIST'), ('NEUROLOGIST', 'neurologist'), ('neurologist', 'neurologist'), ('NEUROLOGIST', 'NEUROLOGIST'), ('OBSTETRICIAN-GYNECOLOGIST', 'obstetrician-gynecologist'), ('obstetrician-gynecologist', 'obstetrician-gynecologist'), ('OBSTETRICIAN-GYNECOLOGIST', 'OBSTETRICIAN-GYNECOLOGIST'), ('ONCOLOGIST', 'oncologist'), ('oncologist', 'oncologist'), ('ONCOLOGIST', 'ONCOLOGIST'), ('OPHTHALMOLOGIST', 'ophthalmologist'), ('ophthalmologist', 'ophthalmologist'), ('OPHTHALMOLOGIST', 'OPHTHALMOLOGIST'), ('ORTHOPEDIC SURGEON', 'orthopedic surgeon'), ('orthopedic surgeon', 'orthopedic surgeon'), ('ORTHOPEDIC SURGEON', 'ORTHOPEDIC SURGEON'), ('PEDIATRICIAN', 'pediatrician'), ('pediatrician', 'pediatrician'), ('PEDIATRICIAN', 'PEDIATRICIAN'), ('PULMONOLOGIST', 'pulmonologist'), ('pulmonologist', 'pulmonologist'), ('PULMONOLOGIST', 'PULMONOLOGIST'), ('PSYCHIATRIST', 'psychiatrist'), ('psychiatrist', 'psychiatrist'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('RADIOLOGIST', 'radiologist'), ('radiologist', 'radiologist'), ('RADIOLOGIST', 'RADIOLOGIST'), ('RHEUMATOLOGIST', 'rheumatologist'), ('rheumatologist', 'rheumatologist'), ('RHEUMATOLOGIST', 'RHEUMATOLOGIST'), ('UROLOGIST', 'urologist'), ('urologist', 'urologist'), ('UROLOGIST', 'UROLOGIST')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
